"Wrap lines at word boundaries - not as useful in console, but good for MacVim.
set wrap
set formatoptions=l
set lbr

set spell
set guioptions-=T  "Don't show toolbar.
set guifont=Monaco:h13"
colorscheme thegoodluck
