"My .vimrc file - used in Linux and OS X.

set nocompatible  "Don't behave in a strong vi-compatible way, apparently.
"Stuff from Rick's .vimrc file.
runtime! debian.vim
syntax on
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif
if has("autocmd")
  filetype indent on
  set autoindent    " always set autoindenting on
endif
set incsearch   " Incremental search
set ts=2
set sw=2
set hlsearch

set expandtab
set softtabstop=2
"au BufEnter *.c setl noexpandtab softtabstop=4
"au BufEnter *.rb setl expandtab softtabstop=2

set wildmode=longest,list

set nowrap  "Don't wrap lines.
set backspace=indent,eol,start
set ruler "Show the cursor position all the time


if has('mouse')
  set mouse=a
endif

" F7: Toggle list mode (aka. visible whitespace)
set listchars=tab:>-,trail:·,eol:$
nnoremap \tl :set invlist list?<CR>
nmap <F7> \tl

"Ignore case when searching.
set ignorecase
set smartcase

"How many file lines per scroll.
set scrolloff=3

"From stackoverflow: make the terminal tab show the filename.
let &titlestring = expand("%:t")
if &term == "screen"
  set t_ts=^[k
  set t_fs=^[\
endif
if &term == "screen" || &term == "xterm"
  set title
endif

"Use the well known ir_black colorscheme in colors dir.
:colorscheme ir_black

"Map semicolon to colon to avoid extra shift when entering command mode.
nmap ; :

"Toggle on/off insert paste mode.
set pastetoggle=<F2>

"Nerdtree stuff.
nmap , :NERDTreeToggle<CR>

"Function to toggle line numbers.
set number  "Show line numbers.
map <F4> :set number!<CR>

"Function to toggle mouse setting.
nnoremap <F3> :call ToggleMouse()<CR>
function! ToggleMouse()
  if &mouse == 'a'
    set mouse=r
    echo "Mouse set to r (for paste to external)"
  else
    set mouse=a
    echo "Mouse set to a (use mouse for -- VISUAL -- selection)"
  endif
endfunction
"Disable the arrow keys to force myself to use navigation!
"inoremap  <Up>     <NOP>
"inoremap  <Down>   <NOP>
"inoremap  <Left>   <NOP>
"inoremap  <Right>  <NOP>
"noremap   <Up>     <NOP>
"noremap   <Down>   <NOP>
"noremap   <Left>   <NOP>
"noremap   <Right>  <NOP>

" Taken from http://jeetworks.org/node/89
" Use the arrow keys to delete/insert blank lines and indent/dedent.
function! DelEmptyLineAbove()
    if line(".") == 1
        return
    endif
    let l:line = getline(line(".") - 1)
    if l:line =~ '^\s*$'
        let l:colsave = col(".")
        .-1d
        silent normal! <C-y>
        call cursor(line("."), l:colsave)
    endif
endfunction
 
function! AddEmptyLineAbove()
    let l:scrolloffsave = &scrolloff
    " Avoid jerky scrolling with ^E at top of window
    set scrolloff=0
    call append(line(".") - 1, "")
    if winline() != winheight(0)
        silent normal! <C-e>
    endif
    let &scrolloff = l:scrolloffsave
endfunction
 
function! DelEmptyLineBelow()
    if line(".") == line("$")
        return
    endif
    let l:line = getline(line(".") + 1)
    if l:line =~ '^\s*$'
        let l:colsave = col(".")
        .+1d
        ''
        call cursor(line("."), l:colsave)
    endif
endfunction
 
function! AddEmptyLineBelow()
    call append(line("."), "")
endfunction
 
" Arrow key remapping: Up/Dn = move line up/dn; Left/Right = indent/unindent
function! SetArrowKeysAsTextShifters()
    " normal mode
    nmap <silent> <Left> <<
    nmap <silent> <Right> >>
    nnoremap <silent> <Up> <Esc>:call DelEmptyLineAbove()<CR>
    nnoremap <silent> <Down>  <Esc>:call AddEmptyLineAbove()<CR>
    nnoremap <silent> <C-Up> <Esc>:call DelEmptyLineBelow()<CR>
    nnoremap <silent> <C-Down> <Esc>:call AddEmptyLineBelow()<CR>
 
    " visual mode
    vmap <silent> <Left> <
    vmap <silent> <Right> >
    vnoremap <silent> <Up> <Esc>:call DelEmptyLineAbove()<CR>gv
    vnoremap <silent> <Down>  <Esc>:call AddEmptyLineAbove()<CR>gv
    vnoremap <silent> <C-Up> <Esc>:call DelEmptyLineBelow()<CR>gv
    vnoremap <silent> <C-Down> <Esc>:call AddEmptyLineBelow()<CR>gv
 
    " insert mode
    imap <silent> <Left> <C-D>
    imap <silent> <Right> <C-T>
    inoremap <silent> <Up> <Esc>:call DelEmptyLineAbove()<CR>a
    inoremap <silent> <Down> <Esc>:call AddEmptyLineAbove()<CR>a
    inoremap <silent> <C-Up> <Esc>:call DelEmptyLineBelow()<CR>a
    inoremap <silent> <C-Down> <Esc>:call AddEmptyLineBelow()<CR>a
 
    " disable modified versions we are not using
    nnoremap  <S-Up>     <NOP>
    nnoremap  <S-Down>   <NOP>
    nnoremap  <S-Left>   <NOP>
    nnoremap  <S-Right>  <NOP>
    vnoremap  <S-Up>     <NOP>
    vnoremap  <S-Down>   <NOP>
    vnoremap  <S-Left>   <NOP>
    vnoremap  <S-Right>  <NOP>
    inoremap  <S-Up>     <NOP>
    inoremap  <S-Down>   <NOP>
    inoremap  <S-Left>   <NOP>
    inoremap  <S-Right>  <NOP>
endfunction
 
call SetArrowKeysAsTextShifters()

